name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-11
    env:
      ARCHFLAGS: -arch x86_64 -arch arm64

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-darwin

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -U pip setuptools wheel setuptools-rust pytest

      - name: Build wheels
        run: python setup.py bdist_wheel

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./bdist/*.whl
