name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    env:
      ARCHFLAGS: -arch x86_64 -arch arm64
      strategy:
        matrix:
          target:
            - x86_64-apple-darwin
            - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{matrix.target}}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -U pip setuptools wheel setuptools-rust pytest

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
